// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Models;

namespace Zoo.Migrations
{
    [DbContext(typeof(ZooContext))]
    partial class ZooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Zoo.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 13,
                            Gender = "Female",
                            Name = "Gary",
                            Species = "Goose"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            Gender = "Male",
                            Name = "Terry",
                            Species = "Tiger"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Gender = "Male",
                            Name = "Lawrence",
                            Species = "Lion"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 6,
                            Gender = "Male",
                            Name = "Gary2",
                            Species = "Goose"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 39,
                            Gender = "Female",
                            Name = "Penelope",
                            Species = "Peacock"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 25,
                            Gender = "Male",
                            Name = "Zane",
                            Species = "Zebra"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 4,
                            Gender = "Male",
                            Name = "Marcus",
                            Species = "Meerkat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 13,
                            Gender = "Female",
                            Name = "Zoie",
                            Species = "Zebra"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 6,
                            Gender = "Female",
                            Name = "Sydney",
                            Species = "Snake"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 19,
                            Gender = "Female",
                            Name = "Karen",
                            Species = "Kimodo Dragon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
